#+LANGUAGE: en
* Páginas interactivas
** Historietas y Comics
*** Generadores
- http://stripgenerator.com/. Editor http://stripgenerator.com/strip/create/
  - permite a cualquier persona, incluso las personas que dicen que no pueden dibujar, crear un cómic en blanco y negro de buen aspecto. Para crear una tira cómica todo lo que tiene que hacer es seleccionar el número de fotogramas que desee a continuación, arrastre los personajes y objetos en esos marcos. Los menús para los personajes y los objetos son bastante extensos. Una vez que haya seleccionado un personaje u objeto, puede ajustar el tamaño para adaptarse a la escena. Adición de texto es una simple cuestión de la selección de un bocadillo y el texto a escribir. Cuando estés satisfecho con su tira cómica se puede guardar en línea, imprimirlo o incrustarlo en tu blog.
- http://www.comicmaster.org.uk/
  - Es una herramienta gratuita diseñada para que los estudiantes crean cómics en el "estilo de la novela gráfica" recomendado para chicos de 10 a 14 años
- http://www.makebeliefscomix.com/
  - Es una herramienta de creación de cómic gratuita que proporciona a los estudiantes una variedad de plantillas, personajes, para la construcción de sus propias tiras cómicas. Proporciona a los estudiantes personajes pre-dibujadas y cuadros de diálogo que se pueden insertar en cada caja de su tira cómica. Las opciones de edición permiten a los usuarios la flexibilidad para modificar el tamaño de cada personaje y la burbuja de diálogo, llevar adelante los elementos dentro de cada caja, y altera la secuencia de cada caja en la historieta. Los estudiantes que tienen problemas para iniciar una historia pueden acceder a pautas de escritura, permite a los usuarios escribir el diálogo de la historieta en Inglés, español, francés, alemán, italiano, portugués. 
- http://chogger.com/
  - Chogger es una herramienta de creación de comic strip gratuito que ofrece una buena selección de herramientas de edición. Le permite dibujar imágenes desde cero o utilizar las imágenes existentes. Incluso puede conectar su cámara web para capturar imágenes para el uso en sus tiras cómicas. Una vez que haya agregado imágenes a su tira cómica, puede agregar efectos tales como la decoloración y esquemas. Chogger también le permite personalizar la apariencia de cada cuadro en su tira cómica. Las tiras cómicas creadas en Chogger pueden tener tan sólo tres marcos o hasta doce o más marcos.
  - http://www.wittycomics.com/
    - Witty Comics proporciona una plataforma simple que los estudiantes pueden utilizar para crear dos diálogos de los personajes. Para utilizar Comics Witty estudiantes sólo tiene que seleccionar las escenas de fondo pre-dibujadas y los personajes pre-dibujadas que quieren figurar en sus comics. Escribir los diálogos es el elemento creativo que se deja a los estudiantes.
  - http://www.artisancam.org.uk/
    - Cam Artisan es algo más que un creador de cómics, es una colección completa de las actividades de arte en línea. En Cam Artisan estudiantes pueden utilizar la acción de Super Comic Creator para construir un cómic de seis marco. La acción de Super Comic Maker tiene una interfaz de arrastrar y soltar que los estudiantes utilizan para seleccionar un fondo y el carácter de sus cómics. 
- Fuentes:
  - http://www.freetech4teachers.com/2010/12/10-ways-to-create-comics-online.html#.Ui3Vzh-LJRQ
  - http://www.freetech4teachers.com/2009/10/20-ways-to-use-comics-in-your-classroom.html#.Ui3Vzx-LJRQ
  - http://www.freetech4teachers.com/2010/12/write-comics-simple-comic-strip.html#.Ui3V0B-LJRQ
* Audio y Video
** Prácticas del Lenguaje
*** Cuentos
- Corazón delator, Edgar Allan Poe. Relato de Laiseca: http://www.youtube.com/watch?v=qWGKr2D9K1E
- Casa tomada, Julio Cortazar. Relato de Laiseca: http://www.youtube.com/watch?v=3ZtRUjwHV30
- No se culpe a nadie. Julio Cortazar: http://www.youtube.com/watch?v=bQir22O1bxc
- La sirenita, otro final de Elvio Gandolfo. Relato por Aliberti para marca de radio: http://www.youtube.com/watch?v=9UNnydtRen0
- El almohadón de plumas. Horacio Quiroga: http://www.youtube.com/watch?v=wm7W_pVCFOA
- La gallina degollada. Horacio Quiroga. Relato de Laiseca: http://www.youtube.com/watch?v=BeatD1AiRfo
- 
* Juegos online
- [[file:juegos/ResolverMisterios.md][Juegos de Misterios]]
